version: "3"

services:
  sanic:
    build:
      context: .
    container_name: sanic
    restart: always
    command: bash -c "python -m alembic upgrade head &&  python server.py --workers 4"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgres
    networks:
      - app-network

  nginx:
    build:
      context: ./Docker/nginx
    container_name: nginx
    tty: true
    ports:
      - "80:80"
    depends_on:
      - sanic
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dimatech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    tty: true
    ports:
      - "2345:80"
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
